# -*- coding: utf-8 -*-
"""BioTrack.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GuKSZcRjvXyqItdV3W1lvCPMF6sAYkuQ

# BioTrack: Smart Healthcare Monitoring System using HR & SpO₂

This project focuses on building a smart healthcare monitoring system that classifies a person's health condition as **Normal** or **Abnormal** using:

- ❤️ Heart Rate (HR)
- 🫁 Oxygen Saturation (SpO₂)



- Data extracted from PhysioNet dataset (.hea files)
- Machine Learning model trained on HR and SpO₂
- Real-time prediction compatible with sensor data
- Hybrid system using **Machine Learning + Rule-based safety**

---
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import re

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix



from datetime import datetime, timedelta
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib import colors as rl_colors

import joblib

files = [
    ("s10_sit","Sit","S10"),
    ("s10_walk","Walk","S10"),
    ("s10_run","Run","S10"),

    ("s11_sit","Sit","S11"),
    ("s11_walk","Walk","S11"),
    ("s11_run","Run","S11"),

    ("s12_sit","Sit","S12"),
    ("s12_walk","Walk","S12"),
    ("s12_run","Run","S12"),
]

data = []

"""**Extracting HR and SpO₂ from .hea Files**

We read `.hea` files and extract:
- Heart Rate (HR)
- Oxygen Saturation (SpO₂)
"""

def extract_meta(file):
    with open("data/" + file + ".hea", "r") as f:
        text = f.read()

    hr = int(re.search(r'hr_1_start>: (\d+)', text).group(1))
    spo2 = int(re.search(r'spo2_start>: (\d+)', text).group(1))

    return hr, spo2

"""**Creating Dataset**

We convert extracted values into a structured DataFrame with columns: Subject, Activity, HR, SpO₂

"""

for file, activity, subject in files:
    hr, spo2 = extract_meta(file)

    data.append([subject, activity, hr, spo2])

df = pd.DataFrame(data, columns=["Subject","Activity","HR","SpO2"])
df

df = df.drop_duplicates()
df = df.reset_index(drop=True)

print(df)

"""**Data Expansion & Realistic Noise Addition**

Since the dataset is small, we:
- Duplicate data multiple times
- Add random noise to simulate real-world variability

This helps improve model training and avoids overfitting.
"""

df_expanded = pd.concat([df]*50, ignore_index=True)
# Add realistic noise
df_expanded['HR'] += np.random.normal(0, 5, len(df_expanded))
df_expanded['SpO2'] += np.random.normal(0, 1, len(df_expanded))

# Clip values to realistic range
df_expanded['HR'] = df_expanded['HR'].clip(50, 140)
df_expanded['SpO2'] = df_expanded['SpO2'].clip(88, 100)

df_expanded

"""**Exploratory Data Analysis(EDA)**"""

print(df_expanded.describe())

print(df_expanded.info())

print(df_expanded.isnull().sum())

"""**Labeling the Data**

We classify data into: **Normal**, **Abnormal**

Based on:
- Low SpO₂ (<93)
- High HR (>115)

This creates the target variable for machine learning.
"""

def label(row):
    if row['SpO2'] < 95:
        return "Abnormal"
    elif row['HR'] > 100 and row['HR'] < 60:
        return "Abnormal"
    else:
        return "Normal"

df_expanded['Label'] = df_expanded.apply(label, axis=1)

"""**Creating Borderline Data**

We generate borderline cases where:
- HR and SpO₂ are near threshold values

- These are randomly labeled to simulate real-world uncertainty.

- This improves model generalization.
"""

borderline = []

for _ in range(100):
    hr = np.random.randint(95, 115)
    spo2 = np.random.randint(92, 95)

    label = np.random.choice(["Normal","Abnormal"])  # ambiguity

    borderline.append(["Border","Mixed", hr, spo2, label])

df_border = pd.DataFrame(borderline,
                         columns=["Subject","Activity","HR","SpO2","Label"])

"""# Adding Synthetic Abnormal Data

We generate critical health cases with:
- High HR
- Low SpO₂

This ensures the model learns abnormal patterns effectively.
"""

abnormal_data = []

for _ in range(150):
    hr = np.random.randint(110, 140)
    spo2 = np.random.randint(85, 93)

    abnormal_data.append(["Synthetic","Critical", hr, spo2, "Abnormal"])

df_abnormal = pd.DataFrame(
    abnormal_data,
    columns=["Subject","Activity","HR","SpO2","Label"]
)

"""**Final Dataset Preparation**

We combine:
- Normal data
- Borderline data
- Abnormal data
"""

final_df = pd.concat([df_expanded, df_border,
                      df_abnormal],ignore_index=True
)

final_df

print(final_df['Label'].value_counts())

"""**Feature Selection**

We use: HR, SpO₂ as input features for machine learning.

Target: Health condition (Label)

**Train-Test Split**

We divide data into:
- Training set (80%)
- Testing set (20%)
"""

X = final_df[['HR','SpO2']]
y = final_df['Label']

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

"""**Model Training (Random Forest)**

We use Random Forest Classifier because:
- Handles non-linear patterns
- Works well with small datasets
- Robust and accurate

The model learns patterns from HR and SpO₂.
"""

model = RandomForestClassifier(n_estimators=100)
model.fit(X_train, y_train)

print("Model Trained")

y_pred = model.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred))

print(classification_report(y_test, y_pred))

print(confusion_matrix(y_test, y_pred))

"""*Real-Time Prediction (Hybrid System)*

We use a hybrid approach:
-  Rule-based Safety:
        - Detects critical conditions instantly
- Machine Learning:
        - Handles normal and borderline cases
"""

def predict_realtime(hr, spo2):

    hr = max(0,min(hr,220))
    spo2 = max(0, min(spo2,100))
    # Rule-based safety
    if spo2 < 94:
        return "Abnormal (Low SpO2)"

    if hr > 110:
        return "Abnormal (High HR)"

    if hr < 45:
        return "Abnormal (Low HR)"

    # Use DataFrame
    input_df = pd.DataFrame([[hr, spo2]], columns=['HR','SpO2'])

    return model.predict(input_df)[0]

print(predict_realtime(85, 97))
print(predict_realtime(120, 96))
print(predict_realtime(75, 92))


